name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Bump version
        run: mvn versions:set -DnewVersion=\${project.version}-SNAPSHOT

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          commit_message: "Bump version"
